---
driver_plugin: vagrant
driver_config:
  require_chef_omnibus: 11.4.4
  network:
  - [private_network, ip: 33.33.33.10]
  customize:
    cpus: 2
    memory: 1024

platforms:
- name: ubuntu-12.10
  driver_config:
    box: opscode-ubuntu-12.10
    box_url: https://opscode-vm-bento.s3.amazonaws.com/vagrant/opscode_ubuntu-12.10_provisionerless.box
  run_list:
  - recipe[apt]

- name: ubuntu-12.04
  driver_config:
    box: opscode-ubuntu-12.04
    box_url: https://opscode-vm-bento.s3.amazonaws.com/vagrant/opscode_ubuntu-12.04_provisionerless.box
  run_list:
  - recipe[apt]

- name: ubuntu-10.04
  driver_config:
    box: opscode-ubuntu-10.04
    box_url: http://opscode-vm-bento.s3.amazonaws.com/vagrant/opscode_ubuntu-10.04_provisionerless.box
  run_list:
  - recipe[apt]

- name: centos-5.9
  driver_config:
    box: opscode-centos-5.9
    box_url: http://opscode-vm-bento.s3.amazonaws.com/vagrant/opscode_centos-5.9_provisionerless.box

- name: centos-6.4
  driver_config:
    box: opscode-centos-6.4
    box_url: http://opscode-vm-bento.s3.amazonaws.com/vagrant/opscode_centos-6.4_provisionerless.box

suites:
- name: server
  run_list:
  - recipe[jenkins::server]
  attributes: {}

- name: server-proxy-nginx
  run_list:
  - recipe[jenkins::server]
  - recipe[jenkins::proxy_nginx]
  attributes:
    jenkins:
      http_proxy:
        host_name: 33.33.33.10
        variant: nginx

- name: server-proxy-nginx-ssl
  run_list:
  - recipe[jenkins-test::generate_certs]
  - recipe[jenkins::server]
  - recipe[jenkins::proxy_nginx]
  attributes:
    jenkins:
      http_proxy:
        host_name: 33.33.33.10
        variant: nginx
        ssl:
          enabled: true
          redirect_http: true

- name: server-proxy-nginx-basicauth
  run_list:
  - recipe[jenkins::server]
  - recipe[jenkins::proxy_nginx]
  attributes:
    jenkins:
      http_proxy:
        host_name: 33.33.33.10
        variant: nginx
        server_auth_method: basic
        basic_auth_username: foo
        basic_auth_password: bar

- name: server-proxy-apache2
  run_list:
  - recipe[jenkins::server]
  - recipe[jenkins::proxy_apache2]
  attributes:
    jenkins:
      http_proxy:
        host_name: 33.33.33.10
        variant: apache2

- name: server-proxy-apache2-ssl
  run_list:
  - recipe[jenkins-test::generate_certs]
  - recipe[jenkins::server]
  - recipe[jenkins::proxy_apache2]
  attributes:
    jenkins:
      http_proxy:
        host_name: 33.33.33.10
        variant: apache2
        ssl:
          enabled: true
          redirect_http: true

- name: server-proxy-apache2-basicauth
  run_list:
  - recipe[jenkins::server]
  - recipe[jenkins::proxy_apache2]
  attributes:
    jenkins:
      http_proxy:
        host_name: 33.33.33.10
        variant: apache2
        server_auth_method: basic
        basic_auth_username: foo
        basic_auth_password: bar
